[package]
name = "server_leo"
version = "0.1.0"
authors = ["Krahos <krahos@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.6.0"
native-tls = "0.2.3"
threadpool = "1.7.1"