[package]
name = "server_leo"
version = "0.1.0"
authors = ["Krahos <krahos@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.6.0"
async-std = "1.0.1"
async-tls = "0.6.0"
rustls = "0.16"